sonar.projectKey=ecommerce-app
sonar.projectName=Areesha and Co Ecommerce
sonar.sources=ecommerce-final/ecommerce-final-backend,ecommerce-final/ecommerce-final-frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**,**/*.json,**/*.zip
sonar.sourceEncoding=UTF-8
